using System.Data.Common;
using System.Text;
using WebDbViewer.Core;
using WebDbViewer.Core.Ddl;

namespace WebDbViewer.Providers.Postgres;

/// <summary>
/// Генератор DDL PostgreSQL: собирает CREATE TABLE из данных системного каталога,
/// представления/индексы/функции — через готовые определения pg_get_*def.
/// Доступ к каталогу — через <see cref="IPgDdlCatalogReader"/> (подменяется в тестах).
/// </summary>
public sealed class PgDdlGenerator : IDdlGenerator
{
    /// <summary>Провайдер используется только для квотирования идентификаторов (без состояния).</summary>
    private static readonly PostgresProvider Quoting = new();

    private readonly Func<DbConnection, IPgDdlCatalogReader> _readerFactory;

    /// <summary>Боевой конструктор: каталог читается с переданного соединения.</summary>
    public PgDdlGenerator() : this(static c => new PgDdlCatalogReader(c)) { }

    /// <summary>Тестовый конструктор: фабрика подменяет чтение каталога fake-реализацией.</summary>
    public PgDdlGenerator(Func<DbConnection, IPgDdlCatalogReader> readerFactory)
        => _readerFactory = readerFactory;

    public DbKind Kind => DbKind.Postgres;

    // ---------------------------------------------------------------- CREATE TABLE

    public async Task<string> GetTableDdlAsync(DbConnection connection, string schema, string table, CancellationToken ct)
    {
        var reader = _readerFactory(connection);
        var t = await reader.GetTableAsync(schema, table, ct).ConfigureAwait(false)
            ?? throw new DdlObjectNotFoundException($"Таблица «{schema}.{table}» не найдена.");
        return BuildTableDdl(t);
    }

    /// <summary>Сборка CREATE TABLE из данных каталога (детерминированная, тестируется без БД).</summary>
    public static string BuildTableDdl(PgDdlTable t)
    {
        var qualified = Qualify(t.Schema, t.Name);
        var sb = new StringBuilder();
        sb.Append("CREATE TABLE ").Append(qualified).Append(" (");

        var body = new List<string>();

        // Колонки: имя тип [GENERATED …|DEFAULT …] [NOT NULL]
        foreach (var col in t.Columns)
        {
            var line = new StringBuilder("    ").Append(Quote(col.Name)).Append(' ').Append(col.DataType);

            if (col.IsGeneratedStored && col.DefaultExpr is not null)
                line.Append(" GENERATED ALWAYS AS (").Append(col.DefaultExpr).Append(") STORED");
            else if (col.Identity == "a")
                line.Append(" GENERATED ALWAYS AS IDENTITY");
            else if (col.Identity == "d")
                line.Append(" GENERATED BY DEFAULT AS IDENTITY");
            else if (col.DefaultExpr is not null)
                line.Append(" DEFAULT ").Append(col.DefaultExpr);

            if (!col.IsNullable)
                line.Append(" NOT NULL");

            body.Add(line.ToString());
        }

        // Ограничения — готовые определения pg_get_constraintdef.
        foreach (var con in t.Constraints)
            body.Add($"    CONSTRAINT {Quote(con.Name)} {con.Definition}");

        sb.Append('\n').Append(string.Join(",\n", body)).Append("\n)");

        if (t.PartitionKey is not null)
            sb.Append('\n').Append(t.PartitionKey); // PARTITION BY RANGE (…)

        sb.Append(";\n");

        // Индексы (кроме обслуживающих ограничения — те уже описаны CONSTRAINT'ами).
        var standaloneIndexes = t.Indexes.Where(i => !i.IsConstraintIndex).ToList();
        if (standaloneIndexes.Count > 0)
        {
            sb.Append('\n');
            foreach (var idx in standaloneIndexes)
                sb.Append(idx.Definition).Append(";\n");
        }

        // Комментарии на таблицу и колонки.
        var comments = new StringBuilder();
        if (t.Comment is not null)
            comments.Append("COMMENT ON TABLE ").Append(qualified)
                .Append(" IS ").Append(QuoteLiteral(t.Comment)).Append(";\n");
        foreach (var col in t.Columns.Where(c => c.Comment is not null))
            comments.Append("COMMENT ON COLUMN ").Append(qualified).Append('.').Append(Quote(col.Name))
                .Append(" IS ").Append(QuoteLiteral(col.Comment!)).Append(";\n");
        if (comments.Length > 0)
            sb.Append('\n').Append(comments);

        return sb.ToString();
    }

    // ---------------------------------------------------------------- CREATE VIEW

    public async Task<string> GetViewDdlAsync(DbConnection connection, string schema, string view, CancellationToken ct)
    {
        var reader = _readerFactory(connection);
        var v = await reader.GetViewAsync(schema, view, ct).ConfigureAwait(false)
            ?? throw new DdlObjectNotFoundException($"Представление «{schema}.{view}» не найдено.");
        return BuildViewDdl(v);
    }

    /// <summary>Сборка DDL представления из данных каталога.</summary>
    public static string BuildViewDdl(PgDdlView v)
    {
        var qualified = Qualify(v.Schema, v.Name);
        var sb = new StringBuilder();
        sb.Append(v.IsMaterialized
                ? $"CREATE MATERIALIZED VIEW {qualified} AS"
                : $"CREATE OR REPLACE VIEW {qualified} AS")
          .Append('\n')
          .Append(v.Definition.TrimEnd());
        if (!sb.ToString().EndsWith(';'))
            sb.Append(';');
        sb.Append('\n');

        if (v.Comment is not null)
            sb.Append('\n')
              .Append(v.IsMaterialized ? "COMMENT ON MATERIALIZED VIEW " : "COMMENT ON VIEW ")
              .Append(qualified).Append(" IS ").Append(QuoteLiteral(v.Comment)).Append(";\n");

        return sb.ToString();
    }

    // ---------------------------------------------------------------- CREATE INDEX

    public async Task<string> GetIndexDdlAsync(DbConnection connection, string schema, string index, CancellationToken ct)
    {
        var reader = _readerFactory(connection);
        var def = await reader.GetIndexDefinitionAsync(schema, index, ct).ConfigureAwait(false)
            ?? throw new DdlObjectNotFoundException($"Индекс «{schema}.{index}» не найден.");
        return def.TrimEnd().TrimEnd(';') + ";\n";
    }

    // ---------------------------------------------------------------- CREATE FUNCTION / PROCEDURE

    public async Task<string> GetRoutineDdlAsync(
        DbConnection connection, string schema, string routine, DbObjectType routineType, CancellationToken ct)
    {
        var reader = _readerFactory(connection);
        var definitions = await reader.GetRoutineDefinitionsAsync(schema, routine, ct).ConfigureAwait(false);
        if (definitions.Count == 0)
            throw new DdlObjectNotFoundException($"Функция/процедура «{schema}.{routine}» не найдена.");

        // Несколько перегрузок — все определения подряд, разделённые пустой строкой.
        var sb = new StringBuilder();
        foreach (var def in definitions)
        {
            var text = def.TrimEnd();
            sb.Append(text);
            if (!text.EndsWith(';'))
                sb.Append(';');
            sb.Append("\n\n");
        }
        return sb.ToString().TrimEnd() + "\n";
    }

    // ---------------------------------------------------------------- Вспомогательное

    private static string Quote(string identifier) => Quoting.QuoteIdentifier(identifier);

    private static string Qualify(string schema, string name) => $"{Quote(schema)}.{Quote(name)}";

    /// <summary>Строковый литерал PostgreSQL: одинарные кавычки удваиваются.</summary>
    private static string QuoteLiteral(string value) => "'" + value.Replace("'", "''") + "'";
}
