using System.Data.Common;

namespace WebDbViewer.Providers.Postgres;

// ---------------------------------------------------------------------------
// Слой чтения системного каталога PostgreSQL для генерации DDL.
// Выделен в интерфейс, чтобы PgDdlGenerator тестировался без живого соединения
// (fake-каталог в юнит-тестах вместо мока DbConnection).
// ---------------------------------------------------------------------------

/// <summary>Колонка таблицы из каталога (данные для строки CREATE TABLE).</summary>
public sealed record PgDdlColumn
{
    public required string Name { get; init; }
    /// <summary>Тип из pg_catalog.format_type (уже с модификаторами: varchar(100), numeric(10,2)…).</summary>
    public required string DataType { get; init; }
    public bool IsNullable { get; init; } = true;
    /// <summary>Выражение DEFAULT из pg_get_expr(adbin, adrelid); null — нет дефолта.</summary>
    public string? DefaultExpr { get; init; }
    /// <summary>attidentity: "" | "a" (GENERATED ALWAYS) | "d" (GENERATED BY DEFAULT).</summary>
    public string Identity { get; init; } = "";
    /// <summary>attgenerated = 's': вычисляемая колонка (GENERATED ALWAYS AS (expr) STORED, expr в DefaultExpr).</summary>
    public bool IsGeneratedStored { get; init; }
    public string? Comment { get; init; }
}

/// <summary>Ограничение таблицы: тип + готовое определение из pg_get_constraintdef.</summary>
public sealed record PgDdlConstraint
{
    public required string Name { get; init; }
    /// <summary>contype: p (PK), f (FK), u (UNIQUE), c (CHECK), x (EXCLUDE).</summary>
    public required char Type { get; init; }
    /// <summary>Полное определение: pg_get_constraintdef(oid, true).</summary>
    public required string Definition { get; init; }
}

/// <summary>Индекс таблицы: готовый CREATE INDEX из pg_get_indexdef.</summary>
public sealed record PgDdlIndex
{
    public required string Name { get; init; }
    /// <summary>Полный оператор из pg_get_indexdef(indexrelid).</summary>
    public required string Definition { get; init; }
    /// <summary>Индекс обслуживает ограничение (PK/UNIQUE) — в DDL не дублируется.</summary>
    public bool IsConstraintIndex { get; init; }
}

/// <summary>Всё необходимое для сборки CREATE TABLE одной таблицы.</summary>
public sealed record PgDdlTable
{
    public required string Schema { get; init; }
    public required string Name { get; init; }
    /// <summary>relkind: r — таблица, p — секционированная таблица.</summary>
    public char RelKind { get; init; } = 'r';
    /// <summary>Ключ секционирования из pg_get_partkeydef (PARTITION BY …); null — не секционирована.</summary>
    public string? PartitionKey { get; init; }
    public string? Comment { get; init; }
    public required IReadOnlyList<PgDdlColumn> Columns { get; init; }
    public IReadOnlyList<PgDdlConstraint> Constraints { get; init; } = [];
    public IReadOnlyList<PgDdlIndex> Indexes { get; init; } = [];
}

/// <summary>Представление: определение + флаг материализованности.</summary>
public sealed record PgDdlView
{
    public required string Schema { get; init; }
    public required string Name { get; init; }
    /// <summary>Тело SELECT из pg_get_viewdef(oid, true).</summary>
    public required string Definition { get; init; }
    public bool IsMaterialized { get; init; }
    public string? Comment { get; init; }
}

/// <summary>Чтение каталога PostgreSQL в объёме, достаточном для генерации DDL.</summary>
public interface IPgDdlCatalogReader
{
    /// <summary>Таблица с колонками, ограничениями и индексами; null — не найдена.</summary>
    Task<PgDdlTable?> GetTableAsync(string schema, string table, CancellationToken ct);

    /// <summary>Представление (обычное или материализованное); null — не найдено.</summary>
    Task<PgDdlView?> GetViewAsync(string schema, string view, CancellationToken ct);

    /// <summary>Определение индекса (pg_get_indexdef); null — не найден.</summary>
    Task<string?> GetIndexDefinitionAsync(string schema, string index, CancellationToken ct);

    /// <summary>Определения всех перегрузок функции/процедуры (pg_get_functiondef); пусто — не найдена.</summary>
    Task<IReadOnlyList<string>> GetRoutineDefinitionsAsync(string schema, string routine, CancellationToken ct);
}

/// <summary>Реализация чтения каталога поверх открытого соединения.</summary>
public sealed class PgDdlCatalogReader(DbConnection connection) : IPgDdlCatalogReader
{
    public async Task<PgDdlTable?> GetTableAsync(string schema, string table, CancellationToken ct)
    {
        // 1. Само отношение: relkind + ключ секционирования + комментарий.
        char relKind;
        string? partitionKey, comment;
        {
            const string sql = """
                SELECT c.relkind::text,
                       CASE WHEN c.relkind = 'p' THEN pg_catalog.pg_get_partkeydef(c.oid) END,
                       obj_description(c.oid, 'pg_class')
                FROM pg_catalog.pg_class c
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = @schema AND c.relname = @name AND c.relkind IN ('r','p')
                """;
            await using var cmd = CreateCommand(sql, schema, table);
            await using var reader = await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await reader.ReadAsync(ct).ConfigureAwait(false))
                return null;
            relKind = reader.GetString(0)[0];
            partitionKey = reader.IsDBNull(1) ? null : reader.GetString(1);
            comment = reader.IsDBNull(2) ? null : reader.GetString(2);
        }

        // 2. Колонки.
        var columns = new List<PgDdlColumn>();
        {
            const string sql = """
                SELECT a.attname,
                       pg_catalog.format_type(a.atttypid, a.atttypmod),
                       NOT a.attnotnull,
                       pg_catalog.pg_get_expr(d.adbin, d.adrelid),
                       a.attidentity::text,
                       a.attgenerated = 's',
                       col_description(a.attrelid, a.attnum)
                FROM pg_catalog.pg_attribute a
                JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                WHERE n.nspname = @schema AND c.relname = @name AND a.attnum > 0 AND NOT a.attisdropped
                ORDER BY a.attnum
                """;
            await using var cmd = CreateCommand(sql, schema, table);
            await using var reader = await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            while (await reader.ReadAsync(ct).ConfigureAwait(false))
            {
                columns.Add(new PgDdlColumn
                {
                    Name = reader.GetString(0),
                    DataType = reader.GetString(1),
                    IsNullable = reader.GetBoolean(2),
                    DefaultExpr = reader.IsDBNull(3) ? null : reader.GetString(3),
                    Identity = reader.IsDBNull(4) ? "" : reader.GetString(4),
                    IsGeneratedStored = !reader.IsDBNull(5) && reader.GetBoolean(5),
                    Comment = reader.IsDBNull(6) ? null : reader.GetString(6),
                });
            }
        }

        // 3. Ограничения: pg_get_constraintdef отдаёт готовый текст (PK/FK/UNIQUE/CHECK/EXCLUDE).
        var constraints = new List<PgDdlConstraint>();
        {
            const string sql = """
                SELECT con.conname, con.contype::text, pg_catalog.pg_get_constraintdef(con.oid, true)
                FROM pg_catalog.pg_constraint con
                JOIN pg_catalog.pg_class c ON c.oid = con.conrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = @schema AND c.relname = @name AND con.contype IN ('p','f','u','c','x')
                ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 ELSE 3 END, con.conname
                """;
            await using var cmd = CreateCommand(sql, schema, table);
            await using var reader = await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            while (await reader.ReadAsync(ct).ConfigureAwait(false))
            {
                constraints.Add(new PgDdlConstraint
                {
                    Name = reader.GetString(0),
                    Type = reader.GetString(1)[0],
                    Definition = reader.GetString(2),
                });
            }
        }

        // 4. Индексы: pg_get_indexdef отдаёт полный CREATE INDEX; индексы ограничений помечаем.
        var indexes = new List<PgDdlIndex>();
        {
            const string sql = """
                SELECT ic.relname,
                       pg_catalog.pg_get_indexdef(i.indexrelid),
                       EXISTS (SELECT 1 FROM pg_catalog.pg_constraint con WHERE con.conindid = i.indexrelid)
                FROM pg_catalog.pg_index i
                JOIN pg_catalog.pg_class ic ON ic.oid = i.indexrelid
                JOIN pg_catalog.pg_class c ON c.oid = i.indrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = @schema AND c.relname = @name
                ORDER BY ic.relname
                """;
            await using var cmd = CreateCommand(sql, schema, table);
            await using var reader = await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            while (await reader.ReadAsync(ct).ConfigureAwait(false))
            {
                indexes.Add(new PgDdlIndex
                {
                    Name = reader.GetString(0),
                    Definition = reader.GetString(1),
                    IsConstraintIndex = reader.GetBoolean(2),
                });
            }
        }

        return new PgDdlTable
        {
            Schema = schema,
            Name = table,
            RelKind = relKind,
            PartitionKey = partitionKey,
            Comment = comment,
            Columns = columns,
            Constraints = constraints,
            Indexes = indexes,
        };
    }

    public async Task<PgDdlView?> GetViewAsync(string schema, string view, CancellationToken ct)
    {
        const string sql = """
            SELECT c.relkind::text,
                   pg_catalog.pg_get_viewdef(c.oid, true),
                   obj_description(c.oid, 'pg_class')
            FROM pg_catalog.pg_class c
            JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = @schema AND c.relname = @name AND c.relkind IN ('v','m')
            """;
        await using var cmd = CreateCommand(sql, schema, view);
        await using var reader = await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
        if (!await reader.ReadAsync(ct).ConfigureAwait(false))
            return null;
        return new PgDdlView
        {
            Schema = schema,
            Name = view,
            IsMaterialized = reader.GetString(0) == "m",
            Definition = reader.GetString(1),
            Comment = reader.IsDBNull(2) ? null : reader.GetString(2),
        };
    }

    public async Task<string?> GetIndexDefinitionAsync(string schema, string index, CancellationToken ct)
    {
        const string sql = """
            SELECT pg_catalog.pg_get_indexdef(c.oid)
            FROM pg_catalog.pg_class c
            JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = @schema AND c.relname = @name AND c.relkind IN ('i','I')
            """;
        await using var cmd = CreateCommand(sql, schema, index);
        var result = await cmd.ExecuteScalarAsync(ct).ConfigureAwait(false);
        return result as string;
    }

    public async Task<IReadOnlyList<string>> GetRoutineDefinitionsAsync(string schema, string routine, CancellationToken ct)
    {
        const string sql = """
            SELECT pg_catalog.pg_get_functiondef(p.oid)
            FROM pg_catalog.pg_proc p
            JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
            WHERE n.nspname = @schema AND p.proname = @name AND p.prokind IN ('f','p','w')
            ORDER BY p.oid
            """;
        var result = new List<string>();
        await using var cmd = CreateCommand(sql, schema, routine);
        await using var reader = await cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
        while (await reader.ReadAsync(ct).ConfigureAwait(false))
        {
            if (!reader.IsDBNull(0))
                result.Add(reader.GetString(0));
        }
        return result;
    }

    private DbCommand CreateCommand(string sql, string schema, string name)
    {
        var cmd = connection.CreateCommand();
        cmd.CommandText = sql;
        var pSchema = cmd.CreateParameter();
        pSchema.ParameterName = "schema";
        pSchema.Value = schema;
        cmd.Parameters.Add(pSchema);
        var pName = cmd.CreateParameter();
        pName.ParameterName = "name";
        pName.Value = name;
        cmd.Parameters.Add(pName);
        return cmd;
    }
}
